baseURL = 'https://jonathanchinwei.github.io/'
languageCode = 'en-us'
title = 'Jonathan Chin'
theme = 'cactus'

[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[params]
colortheme = "classic"
description = """I'm  Jonathan, an incoming senior at the University of Toronto studying Economics and Data Analytics. I care mostly about markets and development, with prior work experience in equity research and macroeconomic research. I'll be joining BCG Toronto as a Summer Associate in June. 

In a former life I was a debater and coach: in high school, I was a top ten debater at the world championships was thereafter a coach for Team Malaysia 2022. 

Other interests include international relations and Christian apologetics. """

mainSection = "posts"
mainSectionTitle = "Blog"

showAllPostsOnHomePage = false
postsOnHomePage = 5

tagsOverview = false

[[params.social]]
  name = "email"
  link = "jonathan.chin@mail.utoronto.ca" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/jonathanchinwei/"

[[params.social]]
  name = "github"
  link = "https://github.com/jonathanchinwei"